services:
  splatam:
    extends: # Add config for GUIs and useful terminal properties on Ubuntu hosts
      file: ./docker/ros_docker/compose/core-compose.yaml
      service: base-gui-ubuntu

    build: # Build command:   docker compose --progress plain build splatam
      context: .
      target: splatam

    image: bennedh/splatam:splatam

    volumes: # Mount this repository into the container (for file access)
      - .:/docker/splatam
